### ISSUE TITLE
react-loadermixin needs to be a regular dependency, not devDependency

### ISSUE THREAD

**Issue by Pomax** [hzdg/react-imageloader#13]
`react`, `react-loadermixin` and `xtend` are required by the imageloader code, and should be normal dependencies, rather than devDependencies.

**Comment by lettertwo** [comment]
Hmm, well [`xtend`][1] *is* a dependency, while both [`react` and `react-loadermixin`][2] are [peer dependencies][3]. What specific problem have you run in to? I don't think we can make react a hard dependency, since multiple versions of react [cannot co-exist][4] (see [this][5] also) in the same app.

[1]: https://github.com/hzdg/react-imageloader/blob/37430948c38ef6e5691f012c98ce7d8c58c9ea4a/package.json#L47
[2]: https://github.com/hzdg/react-imageloader/blob/37430948c38ef6e5691f012c98ce7d8c58c9ea4a/package.json#L43-L44
[3]: https://docs.npmjs.com/files/package.json#peerdependencies
[4]: https://github.com/facebook/react/issues/1939
[5]: https://github.com/facebook/react/issues/2402

**Comment by Pomax** [comment]
For `react`, that's true, but for `react-loadermixin`, I don't think it is. By its very nature people are already going to have react installed, but `loadermixin` is super specific and none of the React projects I'm working on/with at the moment make use of it, only your mixin, so "npm install react-imageloader" yields a "broken" mixin without manually installing a mixin that serves no purpose other than to make yours work. I'd still recommend moving the loadermixin to the regular dependency list, instead.

**Comment by lettertwo** [comment]
Interesting. AFAIK npm should auto-install peer dependencies if they are missing (at least, until 3.x is released). Is it possible you're running an edge version of npm?

**Comment by Pomax** [comment]
hm, deleted node_modules, pruned package.json, reran it, and you're right: it installed just fine. I guess that means this can be closed, sorry to bother and thanks for the reponse!

**Comment by lettertwo** [comment]
:+1: thanks for providing the sanity check! We may still have to do *something* when the next version of npm is released, since peer dependencies will stop auto-installing then…
